name: 'Babilema'
author: 'ByteBakers'
description: 'An action to statically generate a blog based on your GitHub issues'

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true

  config:
    description: 'The path to the configuration file'
    required: false
    default: '${{ github.workspace }}/.babilema.toml'

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - '--mount'
  - 'type=volume,source=${{ github.workspace }},target=${{ github.workspace }}'
  env:
    CONFIG: '${{ inputs.config }}'
    GITHUB_TOKEN: '${{ inputs.github_token }}'

branding:
  color: 'blue'
  icon: 'edit'
