name: 'Babilema'
author: 'ByteBakers'
description: 'An action to statically generate a blog based on your GitHub issues'

inputs:
  github_token:
    description: 'GitHub token for authentication'
    required: true

  github_context:
    description: 'GitHub context'
    required: true

  commit_message:
    description: 'The commit message to use when pushing the generated files'
    required: false
    default: 'ci: update blog'

  config:
    description: 'The path to the configuration file'
    required: false
    default: ${{ github.workspace }}/.babilema.toml

runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    COMMIT_MESSAGE: ${{ inputs.commit_message }}
    CONFIG: ${{ inputs.config }}
    GITHUB_TOKEN: ${{ inputs.github_token }}
    GITHUB_CONTEXT: ${{ toJson(inputs.github_context) }}

branding:
  color: 'blue'
  icon: 'edit'
